version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:80"
    depends_on:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
      - DYNAMODB_HOST=http://dynamodb:8000

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
